### ISSUE TITLE
What about the "source" option ? 

### ISSUE THREAD

**Issue by jaywax** [thebradleysanders/Monoprice-6-Zone-Audio-Controller#11]
Hi,
First, i would like to thank you for your great job :p
This is more a question than an issue i think, but : 
I've just installed your customize coponment and i can't find anymore the control's source for each amp. 
Is it normal ? 
Thanks !

**Comment by jaywax** [comment]
Don't loose you time, i've didn't done the configuration part for the zone's naming... Sorry, and nice job !

**Comment by jaywax** [comment]
Closed !

**Comment by thebradleysanders** [comment]
Thanks for the kind feedback, I am glad you got it working.
